// Generated by CoffeeScript 1.6.2
(function() {
  var a, b, someObject;

  someObject = {
    a: 'value for a',
    b: 'value for b'
  };

  a = someObject.a, b = someObject.b;

  console.log("a is '" + a + "', b is '" + b + "'");

}).call(this);
